name: 'setup-gh'
description: 'Setup Github CLI on workflows with custom linux container'

branding:
  icon: 'play-circle'
  color: 'blue'
  
inputs:
  repository: 
    description: 'Repository setting for Github CLI'
    required: false
    default: ${{ github.repository }}
  token:
    description: 'Authentication token setting for Github CLI'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:

    # This is only triggered on Linux os, 
    # as the only case for which we need to install gh is 
    # when we use an custom container. 
    # For which only Linux runner can config one.
    - name: Install gh
      if: runner.os == 'Linux'
      shell: bash
      run: bash ./install-linux.sh

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "GH_REPO=${{ inputs.repository }}" >> $GITHUB_ENV
        echo "GH_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV

    - name: Print gh version
      shell: bash
      run: gh --version
