name: 'setup-gh'
description: 'Setup Github CLI'

inputs:
  repository: 
    description: "Repository setting for Github CLI"
    required: false
    default: ${{ github.repository }}
  token:
    description: "Authentication token setting for Github CLI"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Install gh
      shell: bash
      run: |
        type -p gh >/dev/null || bash ./install-linux.sh
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "GH_REPO=${{ inputs.repository }}" >> $GITHUB_ENV
        echo "GH_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
    - name: Print gh version
      shell: bash
      run: gh --version
