name: Test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container: ubuntu:latest # This image will be pulled from docker
    steps: # TODO: ensure there does not already exist gh
      - name: Checkout
        uses: actions/checkout@v3
      - name: Invoke
        uses: ./
      - name: Test
        run: gh --help && env
